export enum PopupType {
  SIGN_TRANSACTION_REVIEW = 'SIGN_TRANSACTION_REVIEW',
  SIGN_MESSAGE_REVIEW = 'SIGN_MESSAGE_REVIEW',
  LOGIN_PASSKEY = 'LOGIN_PASSKEY',
  CREATE_PASSKEY = 'CREATE_PASSKEY',
  OAUTH = 'OAUTH',
  ON_RAMP_TRANSACTION = 'ON_RAMP_TRANSACTION',
  EXPORT_PRIVATE_KEY = 'EXPORT_PRIVATE_KEY',
}
