export enum ModalStep {
  EMAIL_COLLECTION = 'EMAIL_COLLECTION',
  VERIFICATION_CODE = 'VERIFICATION_CODE',
  BIOMETRIC_CREATION = 'BIOMETRIC_CREATION',
  AWAITING_WALLET_CREATION = 'AWAITING_WALLET_CREATION',
  ACCOUNT_CREATION_DONE = 'ACCOUNT_CREATION_DONE',
  BIOMETRIC_LOGIN = 'BIOMETRIC_LOGIN',
  AWAITING_WALLET_RETRIEVAL = 'AWAITING_WALLET_RETRIEVAL',
  LOGIN_DONE = 'LOGIN_DONE',
}
