version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    allow:
      - dependency-name: "@getpara/*"
    reviewers:
      - "jlm0"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    groups:
      para-updates:
        patterns: ["@getpara/*"]
