export enum ModalStep {
  EMAIL_COLLECTION = 'EMAIL_COLLECTION',
  VERIFICATION_CODE = 'VERIFICATION_CODE',
  VERIFICATION_CODE_PHONE = 'VERIFICATION_CODE_PHONE',
  VERIFY_2FA = '2FA',
  VERIFY_2FA_PHONE = '2FA_PHONE',
  RECOVERY_AWAITING = 'RECOVERY_AWAITING',
  RECOVERY_INITIATED = 'RECOVERY_INITIATED',
  RECOVERY_READY = 'RECOVERY_READY',
  LOST_2FA = 'LOST_2FA',
}

export const ModalStepNumber: { [key in ModalStep]: number } = {
  [ModalStep.EMAIL_COLLECTION]: 1,
  [ModalStep.VERIFICATION_CODE]: 2,
  [ModalStep.VERIFICATION_CODE_PHONE]: 2,
  [ModalStep.VERIFY_2FA]: 3,
  [ModalStep.VERIFY_2FA_PHONE]: 3,
  [ModalStep.RECOVERY_AWAITING]: 4,
  [ModalStep.RECOVERY_INITIATED]: 4,
  [ModalStep.RECOVERY_READY]: 4,
  [ModalStep.LOST_2FA]: 4,
};
