[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_tokens = "5gscQip1qnTz73BMcBPn8VQivyW9rLs1sfLoi5tqPuot"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "target/idl/"