import { EnabledFlow } from '@getpara/web-sdk';

export enum ModalStep {
  AUTH_MAIN = 'AUTH_MAIN',
  AUTH_MORE = 'AUTH_MORE',
  EX_WALLET_MORE = 'EX_WALLET_MORE',
  EX_WALLET_SELECTED = 'EX_WALLET_SELECTED',
  VERIFICATIONS = 'VERIFICATIONS',
  EXTERNAL_WALLET_VERIFICATION = 'EXTERNAL_WALLET_VERIFICATION',
  AWAITING_OAUTH = 'AWAITING_OAUTH',
  FARCASTER_OAUTH = 'FARCASTER_OAUTH',
  BIOMETRIC_CREATION = 'BIOMETRIC_CREATION',
  AWAITING_BIOMETRIC_CREATION = 'AWAITING_BIOMETRIC_CREATION',
  PASSWORD_CREATION = 'PASSWORD_CREATION',
  AWAITING_PASSWORD_CREATION = 'AWAITING_PASSWORD_CREATION',
  AWAITING_WALLET_CREATION = 'AWAITING_WALLET_CREATION',
  TELEGRAM_OAUTH = 'TELEGRAM_OAUTH',
  WALLET_CREATION_DONE = 'WALLET_CREATION_DONE',
  SECRET = 'SECRET',
  BIOMETRIC_LOGIN = 'BIOMETRIC_LOGIN',
  AWAITING_BIOMETRIC_LOGIN = 'AWAITING_BIOMETRIC_LOGIN',
  AWAITING_PASSWORD_LOGIN = 'AWAITING_PASSWORD_LOGIN',
  LOGIN_DONE = 'LOGIN_DONE',
  SETUP_2FA = 'SETUP_2FA',
  VERIFY_2FA = 'VERIFY_2FA',
  TWO_FACTOR_DONE = 'TWO_FACTOR_DONE',
  ADD_FUNDS_BUY = 'ADD_FUNDS_BUY',
  ADD_FUNDS_RECEIVE = 'ADD_FUNDS_RECEIVE',
  ADD_FUNDS_WITHDRAW = 'ADD_FUNDS_WITHDRAW',
  ADD_FUNDS_AWAITING = 'ADD_FUNDS_AWAITING',
  ADD_FUNDS_SUCCESS = 'ADD_FUNDS_SUCCESS',
  ADD_FUNDS_FAILURE = 'ADD_FUNDS_FAILURE',
  ACCOUNT_MAIN = 'ACCOUNT_MAIN',
  CHAIN_SWITCH = 'CHAIN_SWITCH',
}

export type ModalStepPropU = keyof typeof ModalStep | ModalStep;

export type ModalStepPropL = Lowercase<ModalStepPropU>;

export type ModalStepProp = ModalStepPropU | ModalStepPropL;

enum AccountStep {
  ACCOUNT_MAIN = 'ACCOUNT_MAIN',
  ADD_FUNDS_BUY = 'ADD_FUNDS_BUY',
  ADD_FUNDS_RECEIVE = 'ADD_FUNDS_RECEIVE',
  ADD_FUNDS_WITHDRAW = 'ADD_FUNDS_WITHDRAW',
  ADD_FUNDS_AWAITING = 'ADD_FUNDS_AWAITING',
  ADD_FUNDS_SUCCESS = 'ADD_FUNDS_SUCCESS',
  ADD_FUNDS_FAILURE = 'ADD_FUNDS_FAILURE',
  CHAIN_SWITCH = 'CHAIN_SWITCH',
}

export const RESET_TO_AUTH_STEPS = [
  ModalStep.EX_WALLET_MORE,
  ModalStep.EX_WALLET_SELECTED,
  ModalStep.VERIFICATIONS,
  ModalStep.EXTERNAL_WALLET_VERIFICATION,
  ModalStep.AWAITING_OAUTH,
  ModalStep.FARCASTER_OAUTH,
  ModalStep.TELEGRAM_OAUTH,
  ModalStep.BIOMETRIC_CREATION,
  ModalStep.AWAITING_BIOMETRIC_CREATION,
  ModalStep.PASSWORD_CREATION,
  ModalStep.AWAITING_PASSWORD_CREATION,
  ModalStep.BIOMETRIC_LOGIN,
  ModalStep.AWAITING_BIOMETRIC_LOGIN,
  ModalStep.AWAITING_PASSWORD_LOGIN,
  ModalStep.AWAITING_WALLET_CREATION,
  ModalStep.AWAITING_WALLET_CREATION,
  ModalStep.WALLET_CREATION_DONE,
  ModalStep.SETUP_2FA,
  ModalStep.VERIFY_2FA,
  ModalStep.TWO_FACTOR_DONE,
  ModalStep.LOGIN_DONE,
];

export const RESET_TO_ACCOUNT_STEPS = [
  ModalStep.ADD_FUNDS_BUY,
  ModalStep.ADD_FUNDS_RECEIVE,
  ModalStep.ADD_FUNDS_WITHDRAW,
  ModalStep.ADD_FUNDS_AWAITING,
  ModalStep.ADD_FUNDS_SUCCESS,
  ModalStep.ADD_FUNDS_FAILURE,
  ModalStep.CHAIN_SWITCH,
];

export const AccountPreviousStep: {
  [key in AccountStep]: ModalStep | undefined;
} = {
  [AccountStep.ACCOUNT_MAIN]: undefined,
  [AccountStep.ADD_FUNDS_BUY]: ModalStep.ACCOUNT_MAIN,
  [AccountStep.ADD_FUNDS_WITHDRAW]: ModalStep.ACCOUNT_MAIN,
  [AccountStep.ADD_FUNDS_RECEIVE]: ModalStep.ACCOUNT_MAIN,
  [AccountStep.ADD_FUNDS_AWAITING]: ModalStep.ADD_FUNDS_BUY,
  [AccountStep.ADD_FUNDS_SUCCESS]: ModalStep.ACCOUNT_MAIN,
  [AccountStep.ADD_FUNDS_FAILURE]: ModalStep.ACCOUNT_MAIN,
  [AccountStep.CHAIN_SWITCH]: ModalStep.ACCOUNT_MAIN,
};

enum SignUpModalStep {
  AUTH_MAIN = 'AUTH_MAIN',
  AUTH_MORE = 'AUTH_MORE',
  EX_WALLET_MORE = 'EX_WALLET_MORE',
  EX_WALLET_SELECTED = 'EX_WALLET_SELECTED',
  VERIFICATIONS = 'VERIFICATIONS',
  EXTERNAL_WALLET_VERIFICATION = 'EXTERNAL_WALLET_VERIFICATION',
  AWAITING_OAUTH = 'AWAITING_OAUTH',
  FARCASTER_OAUTH = 'FARCASTER_OAUTH',
  TELEGRAM_OAUTH = 'TELEGRAM_OAUTH',
  BIOMETRIC_CREATION = 'BIOMETRIC_CREATION',
  AWAITING_BIOMETRIC_CREATION = 'AWAITING_BIOMETRIC_CREATION',
  PASSWORD_CREATION = 'PASSWORD_CREATION',
  AWAITING_PASSWORD_CREATION = 'AWAITING_PASSWORD_CREATION',
  AWAITING_WALLET_CREATION = 'AWAITING_WALLET_CREATION',
  WALLET_CREATION_DONE = 'WALLET_CREATION_DONE',
  SECRET = 'SECRET',
  SETUP_2FA = 'SETUP_2FA',
  VERIFY_2FA = 'VERIFY_2FA',
  TWO_FACTOR_DONE = 'TWO_FACTOR_DONE',
  ADD_FUNDS_BUY = 'ADD_FUNDS_BUY',
  ADD_FUNDS_RECEIVE = 'ADD_FUNDS_RECEIVE',
  ADD_FUNDS_WITHDRAW = 'ADD_FUNDS_WITHDRAW',
  ADD_FUNDS_AWAITING = 'ADD_FUNDS_AWAITING',
  ADD_FUNDS_SUCCESS = 'ADD_FUNDS_SUCCESS',
  ADD_FUNDS_FAILURE = 'ADD_FUNDS_FAILURE',
}

export const SignUpPreviousStep: {
  [key in SignUpModalStep]: ModalStep | undefined;
} = {
  [SignUpModalStep.AUTH_MAIN]: undefined,
  [SignUpModalStep.AUTH_MORE]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.EX_WALLET_MORE]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.EX_WALLET_SELECTED]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.VERIFICATIONS]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.EXTERNAL_WALLET_VERIFICATION]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.AWAITING_OAUTH]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.TELEGRAM_OAUTH]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.FARCASTER_OAUTH]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.BIOMETRIC_CREATION]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.AWAITING_BIOMETRIC_CREATION]: ModalStep.BIOMETRIC_CREATION,
  [SignUpModalStep.PASSWORD_CREATION]: ModalStep.BIOMETRIC_CREATION,
  [SignUpModalStep.AWAITING_PASSWORD_CREATION]: ModalStep.BIOMETRIC_CREATION,
  [SignUpModalStep.AWAITING_WALLET_CREATION]: undefined,
  [SignUpModalStep.WALLET_CREATION_DONE]: undefined,
  [SignUpModalStep.SECRET]: undefined,
  [SignUpModalStep.SETUP_2FA]: ModalStep.SECRET,
  [SignUpModalStep.VERIFY_2FA]: ModalStep.SETUP_2FA,
  [SignUpModalStep.TWO_FACTOR_DONE]: undefined,
  [SignUpModalStep.ADD_FUNDS_BUY]: ModalStep.WALLET_CREATION_DONE,
  [SignUpModalStep.ADD_FUNDS_RECEIVE]: ModalStep.WALLET_CREATION_DONE,
  [SignUpModalStep.ADD_FUNDS_WITHDRAW]: ModalStep.WALLET_CREATION_DONE,
  [SignUpModalStep.ADD_FUNDS_AWAITING]: ModalStep.ADD_FUNDS_BUY,
  [SignUpModalStep.ADD_FUNDS_SUCCESS]: undefined,
  [SignUpModalStep.ADD_FUNDS_FAILURE]: undefined,
};

enum LoginModalStep {
  AUTH_MAIN = 'AUTH_MAIN',
  AUTH_MORE = 'AUTH_MORE',
  EX_WALLET_MORE = 'EX_WALLET_MORE',
  EX_WALLET_SELECTED = 'EX_WALLET_SELECTED',
  AWAITING_OAUTH = 'AWAITING_OAUTH',
  FARCASTER_OAUTH = 'FARCASTER_OAUTH',
  TELEGRAM_OAUTH = 'TELEGRAM_OAUTH',
  BIOMETRIC_LOGIN = 'BIOMETRIC_LOGIN',
  AWAITING_BIOMETRIC_LOGIN = 'AWAITING_BIOMETRIC_LOGIN',
  AWAITING_PASSWORD_LOGIN = 'AWAITING_PASSWORD_LOGIN',
  AWAITING_WALLET_CREATION = 'AWAITING_WALLET_CREATION',
  WALLET_CREATION_DONE = 'WALLET_CREATION_DONE',
  SECRET = 'SECRET',
  SETUP_2FA = 'SETUP_2FA',
  VERIFY_2FA = 'VERIFY_2FA',
  TWO_FACTOR_DONE = 'TWO_FACTOR_DONE',
  LOGIN_DONE = 'LOGIN_DONE',
  ADD_FUNDS_BUY = 'ADD_FUNDS_BUY',
  ADD_FUNDS_RECEIVE = 'ADD_FUNDS_RECEIVE',
  ADD_FUNDS_WITHDRAW = 'ADD_FUNDS_WITHDRAW',
  ADD_FUNDS_AWAITING = 'ADD_FUNDS_AWAITING',
  ADD_FUNDS_SUCCESS = 'ADD_FUNDS_SUCCESS',
  ADD_FUNDS_FAILURE = 'ADD_FUNDS_FAILURE',
}

export const LoginPreviousStep: {
  [key in LoginModalStep]: ModalStep | undefined;
} = {
  [LoginModalStep.AUTH_MAIN]: undefined,
  [LoginModalStep.AUTH_MORE]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.EX_WALLET_MORE]: ModalStep.AUTH_MAIN,
  [SignUpModalStep.EX_WALLET_SELECTED]: ModalStep.AUTH_MAIN,
  [LoginModalStep.TELEGRAM_OAUTH]: ModalStep.AUTH_MAIN,
  [LoginModalStep.AWAITING_OAUTH]: ModalStep.AUTH_MAIN,
  [LoginModalStep.FARCASTER_OAUTH]: ModalStep.AUTH_MAIN,
  [LoginModalStep.BIOMETRIC_LOGIN]: ModalStep.AUTH_MAIN,
  [LoginModalStep.AWAITING_BIOMETRIC_LOGIN]: ModalStep.BIOMETRIC_LOGIN,
  [LoginModalStep.AWAITING_PASSWORD_LOGIN]: ModalStep.BIOMETRIC_LOGIN,
  [LoginModalStep.AWAITING_WALLET_CREATION]: undefined,
  [LoginModalStep.WALLET_CREATION_DONE]: undefined,
  [LoginModalStep.SECRET]: undefined,
  [LoginModalStep.SETUP_2FA]: undefined,
  [LoginModalStep.VERIFY_2FA]: ModalStep.SETUP_2FA,
  [LoginModalStep.TWO_FACTOR_DONE]: undefined,
  [LoginModalStep.LOGIN_DONE]: undefined,
  [LoginModalStep.ADD_FUNDS_BUY]: ModalStep.LOGIN_DONE,
  [LoginModalStep.ADD_FUNDS_RECEIVE]: ModalStep.LOGIN_DONE,
  [LoginModalStep.ADD_FUNDS_WITHDRAW]: ModalStep.LOGIN_DONE,
  [LoginModalStep.ADD_FUNDS_AWAITING]: ModalStep.ADD_FUNDS_BUY,
  [LoginModalStep.ADD_FUNDS_SUCCESS]: undefined,
  [LoginModalStep.ADD_FUNDS_FAILURE]: undefined,
};

export const getStepHasFooter = (step: ModalStep): boolean => {
  switch (step) {
    case ModalStep.AUTH_MAIN:
    case ModalStep.AUTH_MORE:
    case ModalStep.EX_WALLET_MORE:
    case ModalStep.EX_WALLET_SELECTED:
    case ModalStep.VERIFICATIONS: {
      return true;
    }
    default: {
      return false;
    }
  }
};

export function getAddFundsStep(currentTab: EnabledFlow): ModalStep {
  switch (currentTab) {
    case 'BUY':
      return ModalStep.ADD_FUNDS_BUY;
    case 'RECEIVE':
      return ModalStep.ADD_FUNDS_RECEIVE;
    case 'WITHDRAW':
    default:
      return ModalStep.ADD_FUNDS_WITHDRAW;
  }
}

export const IFrameSteps: ModalStep[] = [ModalStep.PASSWORD_CREATION];
