export enum ModalStep {
  EMAIL_COLLECTION = 'EMAIL_COLLECTION',
  VERIFICATION_CODE = 'VERIFICATION_CODE',
  BIOMETRIC_CREATION = 'BIOMETRIC_CREATION',
  AWAITING_WALLET_CREATION = 'AWAITING_WALLET_CREATION',
  AWAITING_WALLET_CREATION_AFTER_LOGIN = 'AWAITING_WALLET_CREATION_AFTER_LOGIN',
  ACCOUNT_CREATION_DONE = 'ACCOUNT_CREATION_DONE',
  BIOMETRIC_LOGIN = 'BIOMETRIC_LOGIN',
  AWAITING_WALLET_RETRIEVAL = 'AWAITING_WALLET_RETRIEVAL',
  LOGIN_DONE = 'LOGIN_DONE',
  SETUP_2FA = 'SETUP_2FA',
  SECRET = 'SECRET'
}

export const ModalStepNumber: { [key in ModalStep]: number } = {
  [ModalStep.EMAIL_COLLECTION]: 1,
  [ModalStep.VERIFICATION_CODE]: 2,
  [ModalStep.BIOMETRIC_CREATION]: 3,
  [ModalStep.AWAITING_WALLET_CREATION]: 3,
  [ModalStep.ACCOUNT_CREATION_DONE]: 5,
  [ModalStep.BIOMETRIC_LOGIN]: 3,
  [ModalStep.AWAITING_WALLET_RETRIEVAL]: 3,
  [ModalStep.AWAITING_WALLET_CREATION_AFTER_LOGIN]: 3,
  [ModalStep.LOGIN_DONE]: 5,
  [ModalStep.SETUP_2FA]: 5,
  [ModalStep.SECRET]: 4,
};
