// Objective-C API for talking to github.com/capsule-org/go-sdk/signer Go package.
//   gobind -lang=objc github.com/capsule-org/go-sdk/signer
//
// File is generated by gobind. Do not edit.

#ifndef __Signer_H__
#define __Signer_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class SignerDKLSSerializableSigner;
@class SignerDKLSSigner;
@class SignerED25519Signer;
@class SignerSerializableSigner;
@class SignerSigner;
@class SignerTransaction;
@protocol SignerTxData;

@interface SignerTxData : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
@end

/**
 * Flattened Signer that's gone through KEYGEN
 */
@interface SignerDKLSSerializableSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull otherId;
@property (nonatomic) NSString* _Nonnull receiverConfig;
@property (nonatomic) NSString* _Nonnull senderConfig;
@property (nonatomic) BOOL isReceiver;
@property (nonatomic) BOOL disableWebSockets;
@end

@interface SignerDKLSSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (BOOL)createAccount:(NSString* _Nullable)protocolId useWebSocket:(BOOL)useWebSocket error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getAddress:(NSError* _Nullable* _Nullable)error;
- (BOOL)getDisableWebSockets;
// skipped method DKLSSigner.GetOtherId with unsupported parameter or return types

// skipped method DKLSSigner.GetPartyId with unsupported parameter or return types

// skipped method DKLSSigner.GetPrivateKey with unsupported parameter or return types

- (NSString* _Nonnull)getPublicKey;
- (NSData* _Nullable)getReceiverConfig:(NSError* _Nullable* _Nullable)error;
// skipped method DKLSSigner.GetReceiverConfigStruct with unsupported parameter or return types

- (NSData* _Nullable)getSenderConfig:(NSError* _Nullable* _Nullable)error;
// skipped method DKLSSigner.GetSenderConfigStruct with unsupported parameter or return types

- (NSString* _Nonnull)getWalletId;
- (BOOL)refreshAccount:(NSString* _Nullable)protocolId useWebSocket:(BOOL)useWebSocket error:(NSError* _Nullable* _Nullable)error;
// skipped method DKLSSigner.SendTransaction with unsupported parameter or return types

// skipped method DKLSSigner.SetPool with unsupported parameter or return types

@end

@interface SignerED25519Signer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ED25519Signer.Id with unsupported type: github.com/taurusgroup/frost-ed25519/pkg/frost/party.ID

// skipped field ED25519Signer.OtherId with unsupported type: github.com/taurusgroup/frost-ed25519/pkg/frost/party.ID

// skipped field ED25519Signer.Output with unsupported type: *github.com/taurusgroup/frost-ed25519/pkg/frost/keygen.Output

@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull host;
- (BOOL)createAccount:(NSString* _Nullable)protocolId error:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)getAddress;
// skipped method ED25519Signer.Sign with unsupported parameter or return types

@end

/**
 * Flattened Signer that's gone through KEYGEN
 */
@interface SignerSerializableSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull walletId;
@property (nonatomic) NSString* _Nonnull id_;
// skipped field SerializableSigner.Ids with unsupported type: []string

@property (nonatomic) long threshold;
// skipped field SerializableSigner.Signers with unsupported type: []string

@property (nonatomic) NSString* _Nonnull config;
@end

@interface SignerSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * *
* Computes an ECDH shared secret between the user's private key and another user's public key
* @param account - the address of the account
* @param publicKey - another user's public key in base64
* @returns the shared secret
 */
- (void)computeSharedSecret;
- (BOOL)createAccount:(NSString* _Nullable)protocolId useWebSocket:(BOOL)useWebSocket error:(NSError* _Nullable* _Nullable)error;
// skipped method Signer.CreateAccountV2 with unsupported parameter or return types

/**
 * *
* Decrypts an ECIES ciphertext
* @param account - the address of the account
* @param ciphertext - the cipher to be decrypted
* @returns the decrypted text
 */
- (void)decrypt;
- (NSString* _Nonnull)getAddress:(NSError* _Nullable* _Nullable)error;
- (NSData* _Nullable)getConfig:(NSError* _Nullable* _Nullable)error;
// skipped method Signer.GetPartyId with unsupported parameter or return types

// skipped method Signer.GetPartyIds with unsupported parameter or return types

- (NSString* _Nonnull)getPublicKey;
- (long)getThreshold;
- (NSString* _Nonnull)getWalletId;
- (BOOL)refreshAccount:(NSString* _Nullable)protocolId useWebSocket:(BOOL)useWebSocket error:(NSError* _Nullable* _Nullable)error;
// skipped method Signer.SendTransaction with unsupported parameter or return types

// skipped method Signer.SetPool with unsupported parameter or return types

/**
 * *
* Sign arbitrary hash
* @param hashHex - input to sign encoded as a hex string
* @param signer - Address of the signer (must be unlocked)
 */
- (void)signHash;
/**
 * *
* Retrieve a session token for the account
*
 */
- (BOOL)unlockAccount:(NSString* _Nullable)r1Signature error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * Source https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go
 */
@interface SignerTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@end

// skipped const ED25519CapsulePartyId with unsupported type: github.com/taurusgroup/frost-ed25519/pkg/frost/party.ID

// skipped const ED25519UserPartyId with unsupported type: github.com/taurusgroup/frost-ed25519/pkg/frost/party.ID


@interface Signer : NSObject
// skipped variable PARTY_IDS with unsupported type: github.com/taurusgroup/frost-ed25519/pkg/frost/party.IDSlice

@end

FOUNDATION_EXPORT NSString* _Nonnull SignerCreateAccount(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable protocolId);

// skipped function CreateProtocol with unsupported parameter or return types


// skipped function CreateWallet with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull SignerDKLSCreateAccount(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable protocolId);

// skipped function DKLSCreateProtocol with unsupported parameter or return types


// skipped function DKLSCreateWallet with unsupported parameter or return types


FOUNDATION_EXPORT SignerDKLSSigner* _Nullable SignerDKLSDeserializeSigner(NSString* _Nullable signerParamsStr, NSString* _Nullable serverUrl, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull SignerDKLSGetAddress(NSString* _Nullable serializedSigner);

FOUNDATION_EXPORT NSString* _Nonnull SignerDKLSRefresh(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable protocolId);

/**
 * *
* Sign a RLP-encoded transaction
* @param txRLPBase64 - The RLP encoded transaction in base64
*                      (base64 is easier to decode in native)
 */
FOUNDATION_EXPORT NSString* _Nonnull SignerDKLSSendTransaction(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable txRLPBase64, NSString* _Nullable protocolId);

// skipped function DKLSSerializeSigner with unsupported parameter or return types


// skipped function DKLSSetNetworkClientTransport with unsupported parameter or return types


/**
 * *
* Sign message
* @param message - The message encoded in base64
*                      (base64 is easier to decode in native)
 */
FOUNDATION_EXPORT NSString* _Nonnull SignerDKLSSignMessage(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable message, NSString* _Nullable protocolId);

// skipped function DKLSSignerParamsFromStr with unsupported parameter or return types


FOUNDATION_EXPORT SignerSigner* _Nullable SignerDeserializeSigner(NSString* _Nullable signerParamsStr, NSString* _Nullable serverUrl, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull SignerED25519CreateAccount(NSString* _Nullable mpcNetworkWSHost, NSString* _Nullable walletId, NSString* _Nullable protocolId);

FOUNDATION_EXPORT SignerED25519Signer* _Nullable SignerED25519DeserializeSigner(NSString* _Nullable serializedSigner, NSError* _Nullable* _Nullable error);

// skipped function ED25519NewSigner with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull SignerED25519SerializeSigner(SignerED25519Signer* _Nullable s, NSError* _Nullable* _Nullable error);

/**
 * *
* Sign
* @param message - The bytes to sign encoded in base64
*                      (base64 is easier to decode in native)
 */
FOUNDATION_EXPORT NSString* _Nonnull SignerED25519Sign(NSString* _Nullable serializedSigner, NSString* _Nullable base64BytesToSign, NSString* _Nullable protocolId);

FOUNDATION_EXPORT NSString* _Nonnull SignerGetAddress(NSString* _Nullable serializedSigner);

// skipped function NewDKLSSigner with unsupported parameter or return types


// skipped function NewSigner with unsupported parameter or return types


FOUNDATION_EXPORT NSString* _Nonnull SignerRefresh(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable protocolId);

/**
 * *
* Sign a RLP-encoded transaction
* @param txRLPBase64 - The RLP encoded transaction in base64
*                      (base64 is easier to decode in native)
 */
FOUNDATION_EXPORT NSString* _Nonnull SignerSendTransaction(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable txRLPBase64, NSString* _Nullable protocolId);

// skipped function SerializeSigner with unsupported parameter or return types


// skipped function SetNetworkClientTransport with unsupported parameter or return types


/**
 * *
* Sign message
* @param message - The message encoded in base64
*                      (base64 is easier to decode in native)
 */
FOUNDATION_EXPORT NSString* _Nonnull SignerSignMessage(NSString* _Nullable serverUrl, NSString* _Nullable serializedSigner, NSString* _Nullable message, NSString* _Nullable protocolId);

FOUNDATION_EXPORT SignerSerializableSigner* _Nullable SignerSignerParamsFromStr(NSString* _Nullable signerParamsStr, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSData* _Nullable SignerTransactionBase64ToBytes(NSString* _Nullable tx, NSError* _Nullable* _Nullable error);

/**
 * *
* Retrieve a session token for the account
*
 */
FOUNDATION_EXPORT BOOL SignerUnlockAccount(NSString* _Nullable config, NSString* _Nullable r1Signature, NSError* _Nullable* _Nullable error);

#endif
