import { generateAction } from './utils.js';

export const signUpOrLogIn = generateAction('signUpOrLogIn');
export const verifyNewAccount = generateAction('verifyNewAccount');
export const waitForLogin = generateAction('waitForLogin');
export const waitForSignup = generateAction('waitForSignup');
export const waitForWalletCreation = generateAction('waitForWalletCreation');
export const verifyOAuth = generateAction('verifyOAuth');
export const verifyFarcaster = generateAction('verifyFarcaster');
export const verifyTelegram = generateAction('verifyTelegram');
export const loginExternalWallet = generateAction('loginExternalWallet');
export const verifyExternalWallet = generateAction('verifyExternalWallet');
export const setup2fa = generateAction('setup2fa');
export const enable2fa = generateAction('enable2fa');
export const verify2fa = generateAction('verify2fa');
export const keepSessionAlive = generateAction('keepSessionAlive');
export const logout = generateAction('logout');
export const resendVerificationCode = generateAction('resendVerificationCode');
export const createWallet = generateAction('createWallet');
export const createWalletPerType = generateAction('createWalletPerType');
export const createPregenWallet = generateAction('createPregenWallet');
export const createPregenWalletPerType = generateAction('createPregenWalletPerType');
export const claimPregenWallets = generateAction('claimPregenWallets');
export const hasPregenWallet = generateAction('hasPregenWallet');
export const updatePregenWalletIdentifier = generateAction('updatePregenWalletIdentifier');
export const signMessage = generateAction('signMessage');
export const signTransaction = generateAction('signTransaction');
export const getWalletBalance = generateAction('getWalletBalance');
