name: para_flutter
description: "A demo app for using Para SDK in Flutter"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  para:
    git:
      url: https://github.com/capsule-org/flutter-sdk.git
      ref: evm-web3-signer
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  font_awesome_flutter: ^10.8.0
  web3dart: ^2.7.3
  solana_web3: ^0.1.3
  flutter_svg: ^2.0.16
  solana: ^0.31.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
dependency_overrides:
  pinenacl: 0.6.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/farcaster.svg
    - lib/assets/metamask_icon.svg
    - lib/assets/phantom_icon.svg
