name: PR Format
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  issue_comment:
    types: [created, edited, deleted]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-checklist:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Get PR description
        id: get-pr-description
        uses: actions/github-script@v5
        with:
          script: |
            const { data } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return Buffer.from(data.body).toString('base64');

      - name: Check checklist completion
        run: |
          description_b64="${{ steps.get-pr-description.outputs.result }}"
          if echo "$description_b64" | base64 --decode | grep -q '\-\ \[\ \]'; then
            echo "Not all checklist items are checked."
            exit 1
          else
            echo "All checklist items are checked."
          fi

  validate-pr-title:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  comment-for-examples-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch PR title, body and comments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.issue.number || github.event.pull_request.number }}
          PR_TITLE=$(gh api repos/${{ github.repository }}/pulls/${PR_NUMBER} --jq '.title')
          PR_BODY=$(gh api repos/${{ github.repository }}/pulls/${PR_NUMBER} --jq '.body')
          COMMENTS=$(gh api repos/${{ github.repository }}/issues/${PR_NUMBER}/comments --jq '.[].body')

          echo "Checking PR title for docs link..."
          echo "PR Title: $PR_TITLE"

          # Check for examples in PR body or comments
          if echo "$PR_BODY" | grep -q -E 'NO EXAMPLES NEEDED|https://github.com/getpara/examples-hub/pull/' || echo "$COMMENTS" | grep -q -E 'NO EXAMPLES NEEDED|https://github.com/getpara/examples-hub/pull/'; then
            echo "Valid comment or body found for examples ✅"
          else
            echo "❌ Link with https://github.com/getpara/examples-hub/pull/ or comment with \"NO EXAMPLES NEEDED\" needed for this PR."
            exit 1
          fi

          # Check for docs in PR title, body or NO DOCS NEEDED in comments/body
          if echo "$PR_TITLE" | grep -q 'https://github.com/capsule-org/docs-mintlify/pull/' || echo "$PR_BODY" | grep -q 'NO DOCS NEEDED' || echo "$COMMENTS" | grep -q 'NO DOCS NEEDED'; then
            echo "Valid docs link found in PR title or NO DOCS NEEDED in body/comment ✅"
          else
            echo "❌ Link with https://github.com/capsule-org/docs-mintlify/pull/ in PR title or \"NO DOCS NEEDED\" in body/comment needed for this PR."
            exit 1
          fi
