# Deploys static content to GitHub Pages for documentation
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Check out User Management Client Git repository
        uses: actions/checkout@v3
        with:
          path: 'user-management-client'
          repository: 'capsule-org/user-management-client'
          ref: main
          ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/setup-node@v1
        with:
          node-version: v18
      - name: Set workflow variables
        id: sets-yarn-cache-dir
        run: |
          echo "yarn-cache-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: ${{ steps.sets-yarn-cache-dir.outputs.yarn-cache-dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn install
        run: |
          yarn remove @usecapsule/user-management-client;
          yarn add file:./user-management-client;
          yarn add typedoc;
          yarn
      - name: Setup deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Release to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
        run: |
          npm install --save-dev --legacy-peer-deps @semantic-release/changelog @semantic-release/git;
          npx semantic-release
      - name: Generate docs
        run: |
          ./node_modules/typedoc/bin/typedoc --out docs src/index.ts --skipErrorChecking --excludeInternal
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
