name: Unit Tests

on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cache key prefix
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "CACHE_KEY_PREFIX=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "CACHE_KEY_PREFIX=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.CACHE_KEY_PREFIX }}
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('packages/**/*.ts') }}-${{ hashFiles('packages/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ env.CACHE_KEY_PREFIX }}
            ${{ runner.os }}-nx-

      - name: Build packages
        run: yarn build
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0
          NODE_OPTIONS: '--max_old_space_size=4096'

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up cache key prefix
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "CACHE_KEY_PREFIX=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "CACHE_KEY_PREFIX=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.CACHE_KEY_PREFIX }}

      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('packages/**/*.ts') }}-${{ hashFiles('packages/**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ env.CACHE_KEY_PREFIX }}

      - name: Build packages
        run: yarn build
        env:
          NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

      - name: Configure puppeteer
        run: npx puppeteer browsers install chrome

      - name: Run tests
        run: yarn test
